import asyncio
import datetime as dt
import os
import uuid
import threading
import random

from gptcher.content.creator import Exercise, TranslationTask, load_all_exercises
from gptcher.evaluate import almost_equal, evaluate
from gptcher.language_codes import code_of
from gptcher.gpt_client import complete, supabase, complete_and_parse_json
from gptcher.content.text_to_voice import read_and_save_voice
from gptcher.content.voice_to_text import transcribe
from gptcher.settings import table_prefix


class MixedLanguageMessage:
    def __init__(
        self,
        text,
        user_id=None,
        sender=None,
        text_en=None,
        text_translated=None,
        voice_url=None,
        session=None,
        created_at=None,
        updated_at=None,
        id=None,
        evaluation=None,
    ):
        self.text = text
        if sender is None:
            self.sender = "Teacher" if user_id is None else "Student"
        else:
            self.sender = sender
        self.text_en = text_en
        self.text_translated = text_translated
        self.voice_url = voice_url
        self.session = session
        self.evaluation = evaluation
        self.id = id

        if created_at:
            self.created_at = created_at
        else:
            self.created_at = dt.datetime.now()

    def to_db(self):
        """Convert the object to a dictionary that can be inserted into the database."""
        data = {
            "text": self.text,
            "sender": self.sender,
            "text_en": self.text_en,
            "text_translated": self.text_translated,
            "session": self.session,
            "evaluation": self.evaluation,
        }
        if self.id:
            data["id"] = self.id
        data = supabase.table(table_prefix + "messages").upsert(data).execute().data[0]
        self.id = data["id"]


class Session:
    """Base class for all states of the conversation flow.

    Child classes:
        - ConversationState
        - VocabTrainingState
        - VocabTrainingCeateState
    """

    def __init__(self, user, session=None, context=None):
        self.user = user
        if session:
            self.session = session
        else:
            self.session = str(uuid.uuid4())
        self.context = context or {}

    @property
    def messages(self):
        """Fetch all messages from the database that correspond to the session."""
        messages_db = (
            supabase.table(table_prefix + "messages")
            .select("*")
            .eq("session", self.session)
            .order("created_at")
            .execute()
            .data
        )
        messages = [MixedLanguageMessage(**message) for message in messages_db]
        return messages

    async def start(self, message_raw: str, voice_url: str):
        raise NotImplementedError()

    async def respond(self, message_raw: str, voice_url: str):
        raise NotImplementedError()


conversation_state_prompt = """You are GPTcher, a funny <language> tutor bot. You teach <language> to a student by having a conversation with them.
Your student sends a message in broken <language> or English (or a mixture of both). In the next line, you repeat the message of the student and correct it in case they made mistakes. Then, you respond like a normal conversation partner. You may also casually advertise to donate to GPTcher's patreon (https://www.patreon.com/user?u=55105539 - share this link) - your creators pay 150€ per month for GPT and currently only get 5€ back.
The complete format is:
-
<intro_message>
...
-
Student: {{message in broken <language> or English, example: 'tu mother'}}
Corrected:  {{repeat the student's message in <language>, example: 'tu madre'}} 
-
Teacher: {{answer to the message in <language>}}
Translated: {{English translation of the answer}}
-
...
The corrected message always means exactly what the student tried to say. The teacher's response is funny, interesting and nice, and never boring. The teacher never asks the student the same question back that they asked the teacher. The teacher also has opinions on everything.
-
"""

conversation_state_prefix = """
Corrected:"""

class ConversationState(Session):
    """The default state of the conversation flow.

    This state is entered when the user is new, or when the user has finished a training session.
    """

    async def start(self):
        """Enter the state.

        When this state is entered, the response is generated by the exiting state.
        """
        response_en = "What would you like to talk about?"
        greetings = {
            "English": response_en,
            "Spanish": "¿De qué le gustaría hablar?",
            "German": "Worüber würdest du gerne sprechen?",
        }
        response = greetings[self.user.language]
        message = MixedLanguageMessage(response, sender="Teacher", session=self.session, text_en=response_en, text_translated=response)
        response = self.render_for_user(message)
        await self.user.reply(response)
        message.to_db()
    
    def render_for_user(self, message):
        return f"<b>{message.text}</b>\n{message.text_en.strip()}"
    
    def render_for_dialogue(self, message):
        if message.sender == "Teacher":
            return f"Teacher: {message.text_translated}\nTranslated: {message.text_en}\n-\n"
        else:
            return f"Student: {message.text}\nCorrected: {message.text_translated}\n-\n"

    def get_prompt(self, new_message):
        """Generate the prompt for the AI to generate a response.

        Args:
            message: The message sent by the user.

        Returns:
            A prompt for the AI to generate a response.
        """
        # Generate prompt
        prompt = conversation_state_prompt
        prompt = prompt.replace("<language>", self.user.language)
        prompt = prompt.replace("<intro_message>", self.render_for_dialogue(self.messages[0]))
        for message in self.messages[-5:]:
            prompt += self.render_for_dialogue(message)
        prompt += f"Student: {new_message.text}\nCorrected:"
        return prompt

    async def respond(self, message_raw: str, voice_url: str):
        """Respond to the message.

        Args:
            message_raw: The message sent by the user.

        Returns:
            A response to the message.
        """
        if voice_url:
            message_raw = transcribe(voice_url, self.user.language)
            await self.user.reply(f"Understood: {message_raw}")
        
        message_raw = message_raw.strip().replace("\n", "")\
            .replace("Teacher:", "teacher")\
            .replace("Student:", "student")\
            .replace("Corrected:", "corrected")\
            .replace("Translated:", "translated")

        message = MixedLanguageMessage(
            text=message_raw, user_id=self.user.user_id, session=self.session, voice_url=voice_url
        )
        prompt = self.get_prompt(message)
        print(prompt)
        override = False
        for attempt in range(3):
            completion = complete(prompt, prefix="", stop="Student:", override=override)
            try:
                if not "Teacher:" in completion:
                    completion = completion + "\n-\nTeacher:"
                    completion = complete(prompt, prefix=completion, stop="Student:")
                if not "Translated:" in completion:
                    completion = completion + "\nTranslated:"
                    completion = complete(prompt, prefix=completion, stop="Student:")
                original_completion = completion
                try:
                    corrected, completion = completion.split("\n-\nTeacher:")
                except:
                    corrected, completion = completion.split("Teacher:")
                    corrected = corrected.strip()
                    completion = completion.strip()
                response_translated, response_en = completion.split("\nTranslated:")
                response_msg = MixedLanguageMessage(
                    response_translated.strip(), sender="Teacher", session=self.session, text_en=response_en.strip(), text_translated=response_translated.strip()
                )
                break
            except Exception as e:
                override = True
                print(e)
                print("---")
                print(prompt)
                print(original_completion)
                if attempt == 2:
                    await self.user.reply("Oops, something went wrong. Please try again.")
        message.text_translated = corrected.strip()
        message.to_db()
        if not almost_equal(message.text, corrected):
            await self.user.reply(f"Corrected: {corrected}")
        await self.user.reply(self.render_for_user(response_msg))
        # Save to database
        response_msg.to_db()
        asyncio.create_task(evaluate(message, self.user.vocabulary))


welcome_message = """Hola! I'm a language tutor bot.
Send me a message in English or Spanish or a mixture of both and I'll correct it and respond to it!

By using correct words you improve your score. You can't see your score yet because this features still needs some work :)

You can also start one of many exercises with /train or train the words you know with /vocab.

Don't send private information to me - your messages are sent to other APIs.

We would love to hear your feedback - join our discord https://discord.gg/7yTjrVjQ

If you like this bot, consider donating to our patreon: patreon.com/user?u=55105539"""


if os.getenv("IS_PROD") != "True":
    welcome_message = "This is a test version of GPTcher. Use https://t.me/GPTcherbot \n" + welcome_message


class WelcomeUser(ConversationState):
    """The default state of the conversation flow.

    This state is entered when the user is new, or when the user has finished a training session.
    """

    async def start(self):
        """Enter the state.

        Returns the welcome message and sets the state to conversation
        """
        message = MixedLanguageMessage(
            text=welcome_message, user_id=self.user.user_id, session=self.session
        )
        message.to_db()
        await self.user.reply(welcome_message)
        new_conversation = ConversationState(self.user)
        await self.user.enter_state(new_conversation)

    async def respond(self, message_raw: str, voice_url: str):
        """Respond to the message.

        Args:
            message_raw: The message sent by the user.

        Returns:
            A response to the message.
        """
        await self.start()


vocab_init_message = """In this task, you are a <language> tutor for a student. You make up a number of sentences that use (some) of the provided vocabulary, and the student has to translate them.

The vocabulary for this session is:
{}
You may also use other words if necessary for the sentence to make sense.

Give the response as a JSON list of 5 sentences, where each sentence is a dictionary with the following keys:
- "id": an enumeration of the sentences, starting at 1
- "english": The English content
- "<language>": The translated content
The output must be complete and valid JSON, with exactly 5 sentence objects.

Output:
""".format

vocab_init_prefix = '''
[
    {
        "id": 1,
        "english": "'''


class VocabTrainingState(ConversationState):
    """Creates an exercise from the vocabulary and starts it.
    """

    async def start(self):
        await self.user.reply("Creating an exercise for you...")
        vocab_str = str(self.user.vocabulary.get_learn_list(5))
        exercise = self.create_exercise(vocab_str)
        session = ExerciseState(self.user, context={"exercise_id": exercise.id})
        await self.user.reply(exercise.task_description)
        await self.user.enter_state(session)
        # create all voice messages
        thread = threading.Thread(target=self.create_voice_messages, args=(exercise,))
        thread.start()
    
    def create_voice_messages(self, exercise):
        """Create voice messages for all tasks in the exercise."""
        for task in exercise.translation_tasks:
            task.voice = read_and_save_voice(task.sentence_translated, task.language)
            print("Created voice message for task", task.id)
            task.to_db()
    
    def create_exercise(self, vocab_str):
        task_description = f"Have a look at these words: \n{vocab_str}"
        prompt = vocab_init_message(vocab_str).replace("<language>", self.user.language)
        tasks = complete_and_parse_json(prompt, prefix=vocab_init_prefix, stop=["\n\n", "..."], max_tokens=1000)
        sentences_en = [task['english'] for task in tasks]
        num_vocab_trainings = 0
        exercise = Exercise.create(
            self.user.language,
            "Vocabulary training",
            "Sentences with words the student learns",
            None,
            num_vocab_trainings,
            task_description,
            None,
            sentences_en,
            user_id=self.user.user_id)
        return exercise

    async def respond(self, message_raw: str, voice_url: str):
        """Respond to the message.

        Args:
            message_raw: The message sent by the user.

        Returns:
            A response to the message.
        """
        # we shouldnt be here, print traceback
        print("VocabTrainingState should not be called with respond")
        from traceback import print_stack
        print_stack()
        await self.start()


class ExerciseState(Session):
    """The state of the conversation flow when the user is translating from English to the target language.

    This state is entered when the user sends a message that starts with the command for translating from English to the target language.
    """

    def __init__(self, user, session=None, context=None):
        self.user = user
        self.exercise = Exercise.from_db(context["exercise_id"])
        if session:
            self.session = session
        else:
            self.session = str(uuid.uuid4())
        context["todo"] = context.get("todo", [])
        self.context = context

    async def start(self):
        """Enter the state.

        Returns the welcome message and sets the state to conversation
        """
        await self.user.reply(f"Translate or transcribe the next sentences.")
        response = await self.target_to_en(self.exercise.translation_tasks[0])
        message = MixedLanguageMessage(
            f"Translate or transcribe the next sentences. \n\n" + response,
            sender="Teacher",
            session=self.session,
        )
        message.to_db()
        # Add todos!
        # One iteration: transcribe or target->en
        todos = [{
                'format': random.choice(['transcribe', 'target_to_en']),
                'id': task.id
            }
            for task in self.exercise.translation_tasks[1:]]
        # One iteration: en->target
        todos += [{
                'format': 'en_to_target',
                'id': task.id
            }
            for task in self.exercise.translation_tasks]

        self.context["todo"] = todos
        self.context["previous"] = {"format": "target_to_en", "id": self.exercise.translation_tasks[0].id}

    async def finish(self):
        """Finish the state.

        Returns the welcome message and sets the state to conversation
        """
        score = 10 * len(self.exercise.translation_tasks)
        await self.user.reply(f"You finished the exercise! You earned {score} points.")
        supabase.table(table_prefix + "finished_exercises").insert(
            [
                {
                    "session_id": self.session,
                    "user_id": self.user.user_id,
                    "exercise_id": self.exercise.id,
                    "score": score,
                }
            ]
        ).execute()
        new_conversation = ConversationState(self.user)
        await self.user.enter_state(new_conversation)
        return

    async def respond(self, message_raw: str, voice_url: str):
        """Respond to the message.

        Args:
            message_raw: The message sent by the user.

        Returns:
            A response to the message.
        """
        message, eval_response = await self.correct_previous(message_raw, voice_url)

        if len(self.context["todo"]) == 0:
            await self.finish()
            return

        next_task = self.context["todo"].pop(0)
        task = TranslationTask.from_db(next_task['id'])
        if next_task['format'] == 'en_to_target':
            response = await self.en_to_target(task)
        elif next_task['format'] == 'target_to_en':
            response = await self.target_to_en(task)
        elif next_task['format'] == 'transcribe':
            response, actual_format = await self.transcribe(task)
            next_task['format'] = actual_format
        

        if self.context["previous"]["format"] == 'en_to_target':
            c_previous = dict(**self.context["previous"])
            async def on_fail():
                self.context["todo"].insert(5, c_previous)
                supabase.table(table_prefix + "session").update({"context": self.context}).eq(
                    "id", self.session
                ).execute()
            asyncio.create_task(evaluate(message, self.user.vocabulary, on_fail))
        
        self.context['previous'] = next_task
        supabase.table(table_prefix + "session").update({"context": self.context}).eq(
            "id", self.session
        ).execute()
        message = MixedLanguageMessage(
            eval_response + "\n" + response, sender="Teacher", session=self.session
        )
        message.to_db()

    async def correct_previous(self, message_raw, voice_url):
        previous = TranslationTask.from_db(self.context["previous"]["id"])
        if self.context["previous"]["format"] == 'en_to_target':
            voice = previous.check_voice()
            if voice:
                await self.user.reply(voice)
        message = MixedLanguageMessage(
            text=message_raw,
            user_id=self.user.user_id,
            session=self.session,
            text_en=previous.sentence_en,
            text_translated=previous.sentence_translated,
            sender="Student",
            voice_url=voice_url,
        )
        message.to_db()
        if self.context["previous"]["format"] == 'en_to_target' or self.context["previous"]["format"] == 'transcribe':
            if message.text:
                if almost_equal(message.text, message.text_translated):
                    eval_message = f"✅ {previous.sentence_translated}"
                else:
                    eval_message = f"🤨 Correct: {previous.sentence_translated}"
            else:
                eval_message = f"🦻 Correct: {previous.sentence_translated}"
        elif self.context["previous"]["format"] == 'target_to_en':
            if almost_equal(message.text, message.text_en):
                eval_message = f"✅ {previous.sentence_en}"
            else:
                eval_message = f"🤨 Correct: {previous.sentence_en}"
        await self.user.reply(eval_message)
        return message, eval_message

    async def en_to_target(self, task):
        response = "\nTranslate: " + task.sentence_en
        await self.user.reply(response)
        return response

    async def target_to_en(self, task):
        response = "\nTranslate: " + task.sentence_translated
        await self.user.reply(response)
        if task.voice:
            await self.user.reply(task.voice)
        return response

    async def transcribe(self, task):
        if task.check_voice() is None:
            response = await self.target_to_en(task)
            return response, 'target_to_en'
        response = "\nWrite what you hear:"
        await self.user.reply(response)
        await self.user.reply(task.voice)
        return response, 'transcribe'
    


def deduplicate(seq, idfun=None):
    seen = set()
    seen_add = seen.add
    return [x for x in seq if not (idfun(x) in seen or seen_add(idfun(x)))]

class ExerciseSelectState(ConversationState):
    """Flow:
    User: /select
    Bot: Here are 10 exercises you can do:
    <topics where the user has not done all exercises>
    Select one by sending the number of the exercise or ask for more with any other reply
    User: more
    Bot: Here are 10 more exercises you can do:
    <topics where the user has not done all exercises>
    Select one by sending the number of the exercise or ask for more with any other reply
    User: 1

    """

    def __init__(self, user, session=None, context=None):
        if context is None:
            context = {"available": {}, "show_min": 1, "show_max": 10}
        super().__init__(user, session, context)

    async def start(self):
        language = self.user.language
        exercises = (
            supabase.table(table_prefix + "exercises")
            .select("*")
            .eq("language", language)
            .is_("user_id", 'null')
            .execute()
            .data
        )
        # Get all done exercises
        done_exercises = (
            supabase.table(table_prefix + "finished_exercises")
            .select("*")
            .eq("user_id", self.user.user_id)
            .execute()
            .data
        )
        done_ids = [exercise["exercise_id"] for exercise in done_exercises]
        available_exercises = [
            exercise for exercise in exercises if exercise["id"] not in done_ids
        ]
        if len(available_exercises) == 0:
            await self.user.reply(
                "You have done all the exercises! Congratulations! You can do some again :)"
            )
            available_exercises = exercises
        available = deduplicate(available_exercises, lambda i: i["topic"])
        self.context["available"] = {
            str(i + 1): {"id": exercise["id"], "topic": exercise["topic"]}
            for i, exercise in enumerate(available)
        }
        print(self.context["available"].keys())
        await self.reply_with_exercises()

    async def reply_with_exercises(self):
        show = ""
        for i in range(self.context["show_min"], self.context["show_max"] + 1):
            if str(i) not in self.context["available"]:
                break
            exercise = Exercise.from_db(self.context["available"][str(i)]["id"])
            show += f"{i}: {exercise.topic} ({exercise.exercise_number})\n"
        if show == "":
            self.context["show_min"] = 1
            self.context["show_max"] = 10
            await self.reply_with_exercises()
            return
        await self.user.reply("Here are some exercises you can do:")
        await self.user.reply(show)
        await self.user.reply(
            "Select one by sending the number of the exercise or ask for more with any other reply"
        )
        supabase.table(table_prefix + "session").update({"context": self.context}).eq(
            "id", self.session
        ).execute()

    async def reply_with_more_exercises(self):
        self.context["show_min"] += 10
        self.context["show_max"] += 10
        await self.reply_with_exercises()

    async def respond(self, message_raw: str, voice_url: str):
        try:
            selected = str(int(message_raw))
            if selected in self.context["available"]:
                exercise = Exercise.from_db(self.context["available"][selected]["id"])
                exercise_state = ExerciseState(
                    self.user, self.session, {"exercise_id": exercise.id}
                )
                await self.user.enter_state(exercise_state)
                return
            else:
                await self.user.reply(
                    "We don't have that exercise. Please select one from the list."
                )
                await self.reply_with_exercises()
                return
        except ValueError:
            await self.reply_with_more_exercises()
            return


states_list = [
    WelcomeUser,
    ConversationState,
    VocabTrainingState,
    ExerciseState,
    ExerciseSelectState,
]
STATES = {state.__name__: state for state in states_list}
